apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "kubernetes.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "kubernetes.name" . }}
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "kubernetes.name" . }}
        heritage: "{{ .Release.Service }}"
        release: "{{ .Release.Name }}"
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: "default"
      nodeSelector:
{{ toYaml .Values.kubernetesDashboardNodeSelector | indent 10 }}
      containers:
      - name: main
        image: "k8s.gcr.io/kubernetes-dashboard-amd64:{{ .Values.kubernetesDashboardImageVersion }}"
        resources:
{{ toYaml .Values.kubernetesDashboardResources | indent 10 }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        ports:
        - name: http
          containerPort: 9090
          protocol: TCP
