kubernetesDashboardImageVersion: "v1.8.3"

kubernetesDashboardNodeSelector:
  - node-role.kubernetes.io/node: "true"

kubernetesDashboardResources:
  limits:
    cpu: 100m
    memory: 50Mi
  requests:
    cpu: 100m
    memory: 50Mi